version: "3.8"

services:
  redis-7000:
    image: redis:7
    container_name: redis-7000
    restart: always
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf",
       "--port", "7000",
       "--cluster-announce-port", "7000",
       "--cluster-announce-bus-port", "17000"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/7000:/data
    ports:
      - "7000:7000"
      - "17000:17000"

  redis-7001:
    image: redis:7
    container_name: redis-7001
    restart: always
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf",
       "--port", "7001",
       "--cluster-announce-port", "7001",
       "--cluster-announce-bus-port", "17001"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/7001:/data
    ports:
      - "7001:7001"
      - "17001:17001"

  redis-7002:
    image: redis:7
    container_name: redis-7002
    restart: always
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf",
       "--port", "7002",
       "--cluster-announce-port", "7002",
       "--cluster-announce-bus-port", "17002"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/7002:/data
    ports:
      - "7002:7002"
      - "17002:17002"

  redis-7003:
    image: redis:7
    container_name: redis-7003
    restart: always
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf",
       "--port", "7003",
       "--cluster-announce-port", "7003",
       "--cluster-announce-bus-port", "17003"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/7003:/data
    ports:
      - "7003:7003"
      - "17003:17003"

  redis-7004:
    image: redis:7
    container_name: redis-7004
    restart: always
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf",
       "--port", "7004",
       "--cluster-announce-port", "7004",
       "--cluster-announce-bus-port", "17004"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/7004:/data
    ports:
      - "7004:7004"
      - "17004:17004"

  redis-7005:
    image: redis:7
    container_name: redis-7005
    restart: always
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf",
       "--port", "7005",
       "--cluster-announce-port", "7005",
       "--cluster-announce-bus-port", "17005"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/7005:/data
    ports:
      - "7005:7005"
      - "17005:17005"

networks:
  default:
    driver: bridge
