server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: WebSocket

  data:
    redis:
      password: myRedisPass123
      cluster:
        nodes:
          - localhost:7000
          - localhost:7001
          - localhost:7002
          - localhost:7003
          - localhost:7004
          - localhost:7005
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 1
          max-wait: 1000ms
